- src/Message.php
> Message::getAttachments confirm to signature

- .travis.yml
- phpunit.xml.dist
> Travis: re-enable code-coverage on scrutinizer

- src/Search/Date/AbstractDate.php
- tests/Search/Date/AbstractDateTest.php
- tests/Search/Date/TestAsset/FooDate.php
Reference: https://tools.ietf.org/html/rfc3501#section-9
Closes:
1. https://github.com/ddeboer/imap/pull/128
1. https://github.com/ddeboer/imap/issues/168
> Search\Date\AbstractDate: fix format to RFC-3501

- src/Mailbox.php
- tests/MailboxTest.php
Closes https://github.com/ddeboer/imap/pull/163
> Mailbox: get status

- src/Message/Part.php
- src/Search/Text/Unkeyword.php
- tests/MessageTest.php
Related to:
1. https://github.com/ddeboer/imap/issues/64
1. https://github.com/ddeboer/imap/pull/116
1. https://github.com/ddeboer/imap/issues/123
Reference: http://c-client.u.washington.narkive.com/vWFHD4E7/what-is-encoding-value-6
> Undefined encoding: throw exception

- src/Message.php
- tests/MessageTest.php
> Add tests for #144 set flags functionalities

- src/Exception/MessageCopyException.php
- src/Message.php
- tests/MessageTest.php
> Implement imap_mail_copy

- src/Message/Headers.php
- src/Parameters.php
- tests/MessageTest.php
Reference: https://github.com/ddeboer/imap/issues/200
> Headers now extends \ArrayIterator

- .php_cs
- src/Connection.php
- src/Exception/AbstractException.php
- src/Mailbox.php
- src/Message.php
- src/Message/AbstractMessage.php
- src/Message/Attachment.php
- src/Message/EmailAddress.php
- src/Message/EmbeddedMessage.php
- src/Message/Headers.php
- src/Message/Part.php
- src/Message/Transcoder.php
- src/MessageIterator.php
- src/Parameters.php
- src/Search/AbstractDate.php
- src/Search/AbstractText.php
- src/Search/LogicalOperator/OrConditions.php
- src/SearchExpression.php
- src/Server.php
- tests/AbstractTest.php
- tests/ConnectionTest.php
- tests/EmbeddedMessageTest.php
- tests/MailboxSearchTest.php
- tests/MailboxTest.php
- tests/MessageTest.php
- tests/ServerTest.php
- tests/TestAsset/UnknownCriterion.php
Added:
1. native_function_invocation
1. php_unit_strict
1. phpdoc_summary
1. yoda_style
> Add more coding-standard rules

- src/Message/AbstractPart.php
- src/Message/PartInterface.php
- tests/MessageTest.php
References:
1. #226 
1. #227 
1. #228
> Do not charset-decode attachments

- .php_cs
- .travis.yml
- .travis/readme-index.php
- README.md
> README.md: add Table of Contents with Travis checker

- README.md
- src/Test/RawMessageIterator.php
- tests/MockabilityTest.php
> Add Mockability helpers and documentation

- src/Message/Transcoder.php
- tests/MessageTest.php
Reference: https://github.com/ddeboer/imap/issues/237
> Relay also iconv during decoding

- src/Message/AbstractMessage.php
- src/Message/BasicMessageInterface.php
- tests/MessageTest.php
- tests/fixtures/missing_from.eml
Reference: https://github.com/ddeboer/imap/issues/241
> Message: From header can be absent

- src/ImapResource.php
- src/Mailbox.php
- tests/MessageTest.php
Reference https://github.com/ddeboer/imap/issues/245
@wujku wanna take a look?
> IMAP resource must be checked at every call for mailbox context

- README.md
- composer.json
- src/Message/Transcoder.php
Thanks to the composer dependencies resolution, this isn't a BC break and doesn't require a major bump:
https://github.com/mojombo/semver/blob/v2.0.0/semver.md#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api
> Require ext-iconv

- README.md
* add info about $message->getFrom()
* add info about text return
relative with #251
> make docs more obvious

- README.md
> README.md: add timeout note

- src/Message/Transcoder.php
- tests/MessageTest.php
Reference: https://github.com/ddeboer/imap/issues/270
> Support Microsoft charset values

- src/Mailbox.php
- src/MailboxInterface.php
- tests/MailboxTest.php
Reference: https://github.com/ddeboer/imap/issues/279
On my PC the internal date parameter generate a Segmentation fault, let's see on Travis...
> Make imap_append() optional arguments reachable

- src/Exception/OutOfBoundsException.php
- src/MessageIterator.php
- tests/MailboxTest.php
Reference: https://github.com/ddeboer/imap/issues/288
> MessageIterator: forbid raw calls

- src/Message/AbstractPart.php
- tests/MessageTest.php
- tests/fixtures/mixed_filename.eml
Reference: https://github.com/ddeboer/imap/issues/297
> Don't handle multiplart as an attachment

- src/Message/AbstractPart.php
Reference: https://github.com/ddeboer/imap/issues/301
> AbstractPart::isAttachment() handle unknown part type

- README.md
- tests/MailboxSearchTest.php
Reference: https://github.com/ddeboer/imap/issues/94#issuecomment-365477515
> README.md: add `Unknown search criterion: OR` note

- src/Server.php
- tests/ServerTest.php
Reference: https://github.com/ddeboer/imap/issues/311
Ping @Jpgemy
> Allow empty port

- src/Message.php
- src/Message/AbstractPart.php
- src/Message/EmbeddedMessage.php
- tests/MailboxTest.php
- tests/MessageTest.php
Gracefully handle:
1. https://github.com/ddeboer/imap/issues/301
1. https://github.com/ddeboer/imap/issues/308
1. https://github.com/ddeboer/imap/issues/310
1. https://github.com/ddeboer/imap/issues/317
And many more.
With this PR, all errors are raised after the first method invocation, so any try/catch can be done inside the foreach and the loop can continue.
> Lazy load Message

- src/Message/AbstractPart.php
- tests/MessageTest.php
- tests/fixtures/boolean_decoded_content.eml
Reference: https://github.com/ddeboer/imap/issues/284
> base64_decode may return false in PHP < 7.1

- src/Connection.php
- src/ImapResource.php
- src/ImapResourceInterface.php
> ImapResource: cache last opened mailbox

- src/Message/AbstractPart.php
- tests/MessageTest.php
- tests/fixtures/nestes_embedded_with_attachment.eml
Reference: #342 
https://secure.php.net/manual/en/function.imap-fetchbody.php#89002
> Fix handle of attachment messages with attachments

- .php_cs
- src/Exception/InvalidHeadersException.php
- src/Message.php
- tests/MessageTest.php
Reference: https://github.com/ddeboer/imap/issues/358
> Handle invalid headers

- src/Message/AbstractPart.php
- src/Message/Parameters.php
- tests/MessageTest.php
- tests/fixtures/attachment_long_filename.eml
> Support RFC2231 attachment filenames

- src/Message/AbstractPart.php
- tests/MessageTest.php
- tests/fixtures/plain_text_attachment.eml
> Handle plain/text attachments without Content-Type header

- src/Server.php
- tests/ServerTest.php
> Add ability to pass options and retries to imap_open

- .travis.yml
- Dockerfile
- README.md
- composer.json
- src/Connection.php
- src/ConnectionInterface.php
- src/ImapResource.php
- src/ImapResourceInterface.php
- src/Mailbox.php
- src/MailboxInterface.php
- src/Message.php
- src/Message/AbstractMessage.php
- src/Message/AbstractPart.php
- src/Message/Attachment.php
- src/Message/AttachmentInterface.php
- src/Message/BasicMessageInterface.php
- src/Message/Parameters.php
- src/Message/PartInterface.php
- src/MessageInterface.php
- tests/MessageTest.php
- tests/ServerTest.php
> Require PHP ^7.1

- README.md
Reference: https://feathub.com/
> Add Feature Requests to README.md

- Dockerfile
- Makefile
- composer.json
- docker-compose.yml
- src/Connection.php
- src/Mailbox.php
- tests/AbstractTest.php
- tests/ConnectionTest.php
- tests/MailboxTest.php
- tests/MessageTest.php
- tests/ServerTest.php
> imap_thread: use absolude ids

- .github/dovecot_install.sh
- .github/workflows/integrate.yaml
- .php_cs
- Dockerfile
- Makefile
- composer-require-checker.json
- composer.json
- phpstan.neon
- src/Mailbox.php
- src/Message.php
- src/Message/Transcoder.php
Fixes https://github.com/ddeboer/imap/issues/481
> [GA] PHP 8 compatibility fix

- src/Message/Transcoder.php
Encountered in Microsoft mail service.
> Add x-mac-ce charset as alias for windows-1250

- src/ImapResource.php
> Suppress internal errors from imap_reopen()

- .github/workflows/ci.yaml
- Makefile
- README.md
- composer.json
- phpstan-baseline.neon
- src/Exception/MessageDeleteException.php
- src/Exception/MessageUndeleteException.php
- src/Message.php
- src/Message/AbstractPart.php
- src/MessageInterface.php
- src/Server.php
- tests/AbstractTestCase.php
> Add PHP 8.4 support, drop PHP 8.2
